#
# 	Voting Bundle
#
#	@copyright	(c) 2023 - 2024 Florian Daeumling, Germany. All right reserved
# 	@license 	https://github.com/toteph42/voting/blob/master/LICENSE
#
contao:
    backend:
        badge_title: develop
        route_prefix: '/admin'
            