#
# 	This File is part of Toteph42 Voting bundle
#
#	@copyright	(c) Florian Daeumling, Germany. All right reserved
# 	@license 	https://github.com/toteph42/voting/blob/master/LICENSE
#
app.controller:
    resource: ../src/Controller
    type: annotation