#
# 	Voting Bundle
#
#	@copyright	(c) 2023 - 2024 Florian Daeumling, Germany. All right reserved
# 	@license 	https://github.com/toteph42/voting/blob/master/LICENSE
#
app.controller:
    resource: ../src/Controller
    type: annotation